[tool.black]
line-length = 79
target-version = ['py39']
include = '\.pyi?$'
exclude = '''
  /(
      \.eggs
    | \.git
    | \.hg
    | \.mypy_cache
    | \.tox
    | \.venv
    | _build
    | buck-out
    | build
    | dist
    | migrations
  )/
'''

[tool.isort]
skip = [".gitignore", ".dockerignore"]
skip_glob = ["*/dist/*", "*/migrations/*"]